# config.yaml
program: 2-train_model.py
method: random
project: NeMo_Megatron_PTuning-demo
name: ptuning_sweep
metric:
  goal: minimize
  name: val_loss
parameters:
  global_batch_size: 
    values: [8, 16, 32]
  micro_batch_size: 
    values: [4, 8, 16]
  lr:
    distribution: uniform
    min: 0.0001
    max: 0.1
  dropout:
    distribution: uniform
    min: 0.0
    max: 1.0
  num_layers:
    values: [2, 4, 8]
  max_epochs:
    values: [5, 10, 15]